### ISSUE TITLE
Cinnabar analysis is outdated in the tutorial demo 

### ISSUE THREAD

**Issue by mariacm12** [OpenFreeEnergy/alchemiscale#268]
I was going through the tutorial [**_Using alchemiscale to evaluate a relative binding free energy network_**](https://docs.alchemiscale.org/en/latest/tutorials/demo/Alchemiscale%20Demo.html#), and noticed that the Advanced example was assuming an older version of cinnabar. 
I'm not sure if this was already in the process of being fixed, but the functions used from FEMap and cinnabar_plotting were deprecated. 

**The following changes fixed the issue for me:**
`fe = cinnabar.wrangle.FEMap('cinnabar_input.csv')`
to `fe = FEMap.from_csv('cinnabar_input.csv')`

And converting the graph to the "legacy" format `graph = fe.to_legacy_graph()`, instead of `graph = fe.graph`

**Comment by IAlibay** [comment]
@dotsdl it sounds like we're duplicating a couple of things here that have a tutorial somewhere in the standard openfe ExampleNotebooks. To avoid things going out of date in multiple places, would it make sense to maybe redirect folks at the end of that tutorial to the standard plotting tutorial?

Maybe there's some extra linking magic that could be done here, @Yoshanuikabundi might know something.

**Comment by dotsdl** [comment]
Closed via #311.
