### ISSUE TITLE
Update `alchemiscale` test suite to use `neo4j` 5.23

### ISSUE THREAD

**Issue by dotsdl** [OpenFreeEnergy/alchemiscale#292]
We currently test against `neo4j` 5.16 in the test suite; we should up this to at lest 5.22, which we are now using in production deployments.

**Comment by ianmkenney** [comment]
Notes from working session

``` 
neo4j version  fail?  reason                                                  
-------------------------------------------------------------------------------
          5.16  no     --                                                      
          5.17  no     --                                                     
          5.18  no     --                                                      
          5.19  yes    ValueError, errors.py 56, split code fails (code was None) 
          5.20  yes    ValueError, errors.py 56, split code fails (code was None) 
          5.21  yes    ValueError, errors.py 56, split code fails (code was None) 
          5.22  yes    ValueError, errors.py 56, split code fails (code was None) 
          5.23  yes    ClientError, http.py 482, rs.audit, _hello                 
          5.24  yes    ClientError, http 482, rs.audit, _hello                 
          5.25  yes    ClientError, http 482, rs.audit, _hello                 
```

1 Code split error
==================

  Note that the code split error occurs within Neo4j.split_code method
  in `py2neo/errors.py'.

  We are going to just start from 5.25 so we'll revisit this if necessary. 


2 ClientError
=============

  Dropped into pdb error returns a message "not found" from neo4j
  database

  request went out to /db/data which no longer exists at the py2neo layer. Switching to
  /db/neo4j/tx with POST method fixed the problem and tests passed.

  Go into `grolt/__init__.py` and rewrite `Neo4jMachine.ping`. Remove use of
  py2neo.

  TODO: implement `_poll_http` and `_poll_bolt` using the official neo4j driver

**Comment by dotsdl** [comment]
This PR will fix this: https://github.com/datryllic/grolt/pull/1
